% Copyright 2024 The MathWorks, Inc.
if ~contains(path, fullfile(pwd, '..', 'function_folder'))
    addpath(fullfile(pwd, '..', 'function_folder'));
end
if ~contains(path, fullfile(pwd, '..', 'scripts'))
    addpath(fullfile(pwd, '..', 'scripts'));
end

matlab2simulink_dpigen(...
    functionname = 'add_sub',...
    ctrlports = {'mode'}, ...
    inputargs = {true, uint8(1), uint8(0)}, ...
    DPIFixedPointDataType = 'BitVector', ...
    outputfolder = 'add_sub_builddir', ...
    makeTB = true);

