% Copyright 2024 The MathWorks, Inc.

generate_uvm_component(...
    FunctionName = 'myfunction1', ...
    CodegenDir = 'myfunction1_build', ...
    TemplateFile = 'uvm_component_template.txt', ...
    ClassName = 'refmod', ...
    ClassDir = 'output')
